import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Poppins,
  Montserrat,
  Oxanium,
} from "next/font/google";

import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import NavTracker from "@/hooks/NavTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// New fonts
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const oxanium = Oxanium({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-oxanium",
});
export const metadata: Metadata = {
  title: "MERN | PORTFOLIO",
  description: "Generated by SAKIB HASAN",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${oxanium.variable}  antialiased animated-bg min-h-screen w-full`}
      >
        <NavTracker />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
